version: '3.9'

services:
  db:
    image: postgres:16.3-alpine
    restart: unless-stopped
    expose:
      - '${DB_PORT}'
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file: .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    healthcheck:
      test: ['CMD', 'pg_isready', '-U ${DB_USER}', '-d ${DB_NAME}']
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 5s

volumes:
  db-data:
